[network_custom_fields]
REGEX = \[Network-log\]:\sUser named\s(.+?)\sfrom\s(.+?)\sdepartment accessed the resource\s([^/\s]+)(/\S+)\sfrom the source IP\s(\d{1,3}(?:\.\d{1,3}){3})\sand country\s+([A-Za-z ]+?)\sat:
FORMAT = Username::$1 Department::$2 Domain::$3 URI::$4 SourceIP::$5 Country::$6
WRITE_META = true
