[script:///opt/splunk/etc/apps/DataApp/bin/samplelogs.py]
disabled = 0
index = main
sourcetype = testing
host = test
interval = 5

[script:///opt/splunk/etc/apps/DataApp/bin/vpnlogs]
disabled = 0
index = main
sourcetype = vpn_logs
host = vpn_server
interval = 5

[script:///opt/splunk/etc/apps/DataApp/bin/authentication_logs]
disabled = 0
index = main
sourcetype = auth_logs
host = auth_server
interval = 5

[script:///opt/splunk/etc/apps/DataApp/bin/purchase-details]
disabled = 0
index = main
sourcetype = purchase_logs
host = order_server
interval = 5
